### ISSUE TITLE
Add a setting "chance of a helicopter crash" please 

### ISSUE THREAD

**Issue by DestroClub** [sharkster91/ExpandedHelicopterEvents#11]
Cut off day - 14 
THE LAST DAY 14 | outside HEAVY THUNDER with the rain | 
And what do I see in the log file? Chance to crash 40 ))))))) 40 Carl and... no one crash
Guys I'm ready to beg I just wanna see helicrash in MY GAME SESSION like in Arma 2 DayZ mod
Please give an opportunity to an old veteran DayZ 
Just one setting please

**Comment by ChuckTheSheep** [comment]
See #12
