### ISSUE TITLE
Possible bug with crafting since 8/5 mod update

### ISSUE THREAD

**Issue by mjv96** [sharkster91/ExpandedHelicopterEvents#22]
As I had stated in my message in steam, prior to the update around 9:45a EST, I could and did craft walls and such. After the update, it will let me craft (it goes through the motion) BUT nothing shows up. Just an red error box in the corner. The only STACK TRACE error I could find, and the only one that shows up in debug mode when I try to craft with carpentry is:

STACK TRACE
-----------------------------------------
function: create -- file: ISSimpleFurniture.lua line # 13
function: perform -- file: ISBuildAction.lua line # 119

LOG  : General     , 1628179907753> Object tried to call nil in create
LOG  : General     , 1628179907840> creating new sourcewindow: C:/Games/Steam/steamapps/common/ProjectZomboid/media/lua/server/BuildingObjects/ISSimpleFurniture.lua

I'll try the usual verify files, etc, and even try redownloading this mod again just to be safe. Mind you, I was ok till this mod was updated so I'm utterly baffled.

**Comment by ChuckTheSheep** [comment]
That's not a file that is modified by this mod - it is in-fact a vanilla file. Could you provide the log file here in it's entirety?

**Comment by mjv96** [comment]
I thought it was a vanilla file. Let me see if I can attach the console.txt file. It was way to large to paste (Tried that earlier).
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/6942919/console.txt)

**Comment by ChuckTheSheep** [comment]
STACK TRACE
-----------------------------------------
Callframe at: setMutualExclusive
function: doTraits -- file: 2ProfessionFramework.lua line # 165
-----------------------------------------
attempted index: items of non-table: null
function: AlarmCheckItemDistributions.lua -- file: AlarmCheckItemDistributions.lua line # 3
-----------------------------------------
Callframe at: table.insert
function: AirHorn_Distributions.lua -- file: AirHorn_Distributions.lua line # 6
-----------------------------------------
Callframe at: table.insert
function: FMJlockPicking_Distributions.lua -- file: FMJlockPicking_Distributions.lua line # 7
-----------------------------------------
Callframe at: table.insert
function: ForkMJfoodWild_Distributions.lua -- file: ForkMJfoodWild_Distributions.lua line # 7
-----------------------------------------
function: HurleyFishing_Distributions.lua -- file: HurleyFishing_Distributions.lua line # 17
-----------------------------------------
function: LabDistributions.lua -- file: LabDistributions.lua line # 48
-----------------------------------------
function: RthConmagdistribution.lua -- file: RthConmagdistribution.lua line # 10
-----------------------------------------
function: RthVinmagdistribution.lua -- file: RthVinmagdistribution.lua line # 10
-----------------------------------------
function: create -- file: ISWoodenFloor.lua line # 13
function: perform -- file: ISBuildAction.lua line # 119


There are a lot of errors related to distributions which is to be expected for the 41.53 switch. The error related to the building could be from one of those others mod messing with building in some way.

**Comment by mjv96** [comment]
It looks to be fixed for now. Went and redownloaded all 90 of the mods I run and started a new game. So far, so good. Thanks for your help and awesome mod!

**Comment by mjv96** [comment]
It turns out, this issue may be linked to the updated loot tables. This bug was apparently triggered by me not having any nails or enough nails in my inventory. Having a box of nails didn't count.
