### ISSUE TITLE
Stack Trace and Sound Bug

### ISSUE THREAD

**Issue by Banzaikoowaid** [sharkster91/ExpandedHelicopterEvents#23]
Stack Trace contributing to a crash, occuring today (8/7/2021 5:19p.m. CST), on Build 41.53:

LOG  : General     , 1628374769755> -----------------------------------------
STACK TRACE
-----------------------------------------
function: HeliDistItems.lua -- file: HeliDistItems.lua line # 3

Aug 07, 2021 5:19:29 PM zombie.Lua.LuaManager RunLua
SEVERE:  java.lang.RuntimeException
Aug 07, 2021 5:19:29 PM zombie.Lua.LuaManager RunLua
SEVERE: java.lang.RuntimeException: 
Aug 07, 2021 5:19:29 PM zombie.Lua.LuaManager RunLua
SEVERE: at HeliDistItems.lua:3

Note: I did not encounter, see nor hear a helicopter in the game when the stack trace and subsequent crash occurred. Don't know if this helps, but might be important.

Addendum (8/7/2021-6:04p.m. CST): Just want to preemptively mention that I do indeed have Easy Config Chucked (The other required mod for Expanded Helicopter Events to Work) installed and enabled.

Sound Bug: Military Helicopter crashed, but the sound of the helicopter blades whirring was omnipresent for four in-game days until crashing, following me wherever I drove and walked.

**Comment by ChuckTheSheep** [comment]
We do not named our files with out a prefix for easier identification- I don't believe "HeliDistItems" is related to this mod.

As for the sound bug our events don't follow the player around if the event has "crashed" the sound would be fixed to the crash if it didn't stop.

**Comment by Banzaikoowaid** [comment]
I see, hmm. I'll close this then, and thank you for the clerification.
