### ISSUE TITLE
Jet looping sound...never ends.

### ISSUE THREAD

**Issue by mjv96** [sharkster91/ExpandedHelicopterEvents#24]
Ran into this today...but have had it with the helicopters too. Follows me everywhere. For whatever reason, I can't attach the console.txt file. When I try to, I get a red message at the bottom of this text box stating "is not included in the list". There are a TON of error pertaining to this mod towards the bottom though. This file is 42.1mg and takes a bit to open. Let me know if there is another way I can get this console.txt file to you.

This is just one of them:
STACK TRACE
-----------------------------------------
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 111
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 232

LOG  : General     , 1628432601573> Object tried to call nil in update
ERROR: General     , 1628432601573> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Object tried to call nil in update at KahluaUtil.fail line:82.
ERROR: General     , 1628432601574> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: Object tried to call nil in update
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:38)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:88)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1619)
	at zombie.gameStates.IngameState.update(IngameState.java:1319)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:285)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:726)
	at zombie.GameWindow.run_ez(GameWindow.java:642)
	at zombie.GameWindow.mainThread(GameWindow.java:471)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1628432601575> -----------------------------------------
STACK TRACE
-----------------------------------------
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 111
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 232

LOG  : General     , 1628432601575> 
LOG  : General     , 1628432601590> -----------------------------------------
STACK TRACE

**Comment by mjv96** [comment]
I have a hovering copter event now...i'm kinda enjoying it was it's one broadcasting a message but I think i found the error. Line 109 appears to have a space between the " and (square)". should this not be "(square)"? i'm not a coder in any sense of the word but the debugger opened right up to this.
![20210808114934_1](https://user-images.githubusercontent.com/88501817/128637874-b5211941-9a49-4094-8b92-427aed8c42b0.jpg)

**Comment by ChuckTheSheep** [comment]
I will look into this. Thank you.

**Comment by mjv96** [comment]
Glad to help! =)

**Comment by ChuckTheSheep** [comment]
Just to clarify was this issue resolved? If not can you please drag the console.txt here. It will attach the file.

**Comment by mjv96** [comment]
I'll let you know in the next 24hrs or so. Have to get to work now but I'll let you know ASAP.

**Comment by mjv96** [comment]
Ok, so "KINDA" is the best way for me to describe. The looping sound event is fixed BUT, now, the sound continues on for a bit before ending. By that I mean, the helicopter flies off but the chatter over the speakers (in this case I had a police helicopter fly over with that quarantine message), went through all 4 (I think I heard 4 different voices) scripts, and then there was a "shot" fired and silence. This even followed me perfectly into a building. Normally, the sound is muffled, but not in this case.

I removed the mod and redownloaded it late last night so I know it's the one you updated (plus the looping / following sound is gone).
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/6961744/console.txt)

**Comment by ChuckTheSheep** [comment]
Very strange. Unfortunately the sound is reliant on the vanilla sound functions/systems - and those are known to be spotty. (You may sometimes hear very sharp changes from ear to ear sometimes - this is why.)

**Comment by mjv96** [comment]
Oddly enough, the chatter (quarantine message) started again, well after it finished, inside a train depot bunker without the helicopter flying over. It's like it restarted without the actual helicopter event firing.

**Comment by mjv96** [comment]
Well, this has to have come from the fix. EVERY helicopter event now is like this. I believe the only event now I'm getting is the quarantine message event, though I did have a helicopter crash relatively close to my base spewing Notification pamphlets and supply pallets all over the place.

**Comment by ChuckTheSheep** [comment]
Very strange, I'm not able to replicate this issue. Do you have a mod list handy?

**Comment by mjv96** [comment]
Is there an easy way for me to get you a list? I have around 90 mods running at the moment.

**Comment by ChuckTheSheep** [comment]
Perhaps a screenshot?

**Comment by mjv96** [comment]
Ok, here's the mile long mod list in jpeg form.
![Mod 1](https://user-images.githubusercontent.com/88501817/129031615-b37d3096-3b38-482c-9706-e766637145c9.jpg)

**Comment by ChuckTheSheep** [comment]
There's a mod menu in game, sorry for the work.

**Comment by mjv96** [comment]
LOL...I forgot about that!

**Comment by mjv96** [comment]
Started a brand new game and within 10m of playing, those quarantine messages started to play without a helicopter event even firing off. I checked the command console (running with debug mode on) and definitely no helicopter event has fired yet.

**Comment by ChuckTheSheep** [comment]
Do you play on debug mode? Go to options, in the expanded helicopter tab, and turn off test suite if you do.

**Comment by mjv96** [comment]
ok, i'll give that a whirl.

**Comment by mjv96** [comment]
Ok, tried that and same thing. The quarantine message keeps firing off. Gonna try one other thing though.

**Comment by mjv96** [comment]
yup, so I went and started yet another game after that one. Not even 2 minutes into the game and it's though speakers were in the house i spawned in and it came over. a few game hours later and a helicopter event spawned (quarantine event again) but it was normal. Gonna play this one out for a bit and see what happens.

**Comment by mjv96** [comment]
Well, I've restarted twice since but in both cases and the current game, The random sound clips aren't firing off anymore. I've had a few helicopter events, mainly the quarantine one, and everything is going good. Looks like the issue has been resolved for now. Thanks for the help!!

**Comment by ChuckTheSheep** [comment]
No problem, I just wish I knew what happened. Thank you for your time.
