### ISSUE TITLE
the title menu disappears.

### ISSUE THREAD

**Issue by EekBaalam** [sharkster91/ExpandedHelicopterEvents#26]
Hi!
every time I load the mod, the problem occurs. Attachment. 

https://youtu.be/SFc3hLWkAM0
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7037083/console.txt)

**Comment by ChuckTheSheep** [comment]
I will be looking into this - for the meantime can you try to presubscribe to EasyConfig and try again.

Also, please let me know what other mods you're using - just incase there's a compatibility issue. Thank you!

**Comment by EekBaalam** [comment]
Hello again!
Since I received your reply I have been testing mod by mod, even "swap it" and "auto-eat" make the title screen disappear. I also did what you asked me, it didn't work. Still, thank you very much for your attention.
mods list:
https://youtu.be/0fI-ks13tDo

**Comment by ChuckTheSheep** [comment]
Auto eat doesn't use EasyConfig though. I'd suggest disabling all of your mods except for EasyConfig and Expanded helis and seeing if it happens with just those two.

**Comment by ChuckTheSheep** [comment]
Just updated EasyConfig again slightly - try to resubscribe/redownload it again.
