### ISSUE TITLE
Constant supply drops

### ISSUE THREAD

**Issue by Sonasin** [sharkster91/ExpandedHelicopterEvents#28]
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7359965/console.txt)

**Comment by Sonasin** [comment]
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7359976/console.txt)
Also here's the log after disabling the mod for the save. Don't know if anything will have changed but hope it helps!

**Comment by ChuckTheSheep** [comment]
Thanks! Looking at it now.

**Comment by ChuckTheSheep** [comment]
Let me know if the issue is still around - the scheduler got rewritten.
