### ISSUE TITLE
Choopers Despawn when getting closer (SANDBOX CONFIG?)

### ISSUE THREAD

**Issue by KyubiHitashi** [sharkster91/ExpandedHelicopterEvents#32]
I've Been playing with this mod on Sandbox with certain settings after the EHE Events configs were added on the sandbox mode.

Military : Never
Raiders : Never
Civlians : High
Samaritans : High

For some unknown reason i think, due to the settings the choopers despawn when they arrive, the proper chooper like from Military, Police, they quickly despawn as soon as they get really close to the player, possibly due to a feature or maybe director config from the sandbox???

**Comment by ChuckTheSheep** [comment]
Should have been fixed with the 2 hotfixes. Let me know with a new issue.
