### ISSUE TITLE
multiple helicopters and jets with never ending sirens 

### ISSUE THREAD

**Issue by agooses** [sharkster91/ExpandedHelicopterEvents#33]
this was after the 2 fixes but on an pre fix save which had experienced the bug before. at time of sending the file 2 helicopters where inbound after a game restart to stop the sirens. 
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7587117/console.txt)

**Comment by ChuckTheSheep** [comment]
I don't see any errors on this log file. Further more, there are no scheduling lines present - instead only a few events being launched. (News choppers and a few military.)

Are you using `-debug` mode on? When `-debug` is on and the `debug suite` is toggled on in the menu the 1-0 keys perform tests on events.

**Comment by agooses** [comment]
Sorry I did not realise that you had to be debug.

**Comment by ChuckTheSheep** [comment]
You do not need -debug on. I am confused because your log doesn't show the current update being present. I would suggest resubscribing to make sure you have the latest build.

**Comment by agooses** [comment]
Everything fixed, thank you
