### ISSUE TITLE
No items in air drop

### ISSUE THREAD

**Issue by NinoursTV** [sharkster91/ExpandedHelicopterEvents#34]
Hello,

Like i said you in workshop, all my airdrop are empty. 
My console.txt like you want.

Really good job anyway, it's my best mods ;)

**Comment by NinoursTV** [comment]
Ok, i plays few minutes and call 2 or 3 samaritains in solo and in MP.
In solo, no problems, but in MP airdrop are empty.
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7786368/console.txt)

**Comment by ChuckTheSheep** [comment]
Is this still an issue?
