### ISSUE TITLE
Error message after event

### ISSUE THREAD

**Issue by S1ammu** [sharkster91/ExpandedHelicopterEvents#35]
Noticed there was an update earlier today. Resubscribed to the mod and as I've been playing I've had two events, at the end of each I had 1 error message pop up. Didn't notice anything wrong with the game or the events so not sure what the issue is, just thought I'd report it to you. Thanks, great mod!

[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7831695/console.txt)

**Comment by ChuckTheSheep** [comment]
Should be fixed with the next update.
