### ISSUE TITLE
Military helicopter not leaving

### ISSUE THREAD

**Issue by W2C-2003** [sharkster91/ExpandedHelicopterEvents#38]
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7844369/console.txt)
Military helicopter showed up and has been flying in the same area for the past several days. You asked me to present a console log the next time I had it happen.

**Comment by ChuckTheSheep** [comment]
Unclear what the error might be. A new patch is coming out that should fix a few other issues, let me know if it occurs after that.
