### ISSUE TITLE
Infinite Air Raid Siren Hosted Multiplayer

### ISSUE THREAD

**Issue by DoctorDoomTeddy** [sharkster91/ExpandedHelicopterEvents#41]
Infinite Air Raid Siren, Hosted Multiplayer, carpet bombing run

[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7878901/console.txt)

**Comment by Jesseman1** [comment]
Since I was in the server when this happened I'd like to add some context. The air raid siren played to warn of a bombing run, but never stopped even after the jets passed. The sound stopped when the server was restarted.

**Comment by ChuckTheSheep** [comment]
Thank you. Still looking into it.

**Comment by ChuckTheSheep** [comment]
Please confirm if this happens again with today's update.
