### ISSUE TITLE
Error after the last update

### ISSUE THREAD

**Issue by qestsmile** [sharkster91/ExpandedHelicopterEvents#42]
This - https://paste.in/RFEVDf

**Comment by ChuckTheSheep** [comment]
Confirm the line in your log starting with: `Expanded Helicopter Events: ver:` 
How does it end?

**Comment by AdeptSephiel** [comment]
For me it's `0.3.5`
However this error was prior to the most recent update and seems to have fixed it. I'll let you know if it happens again though.

**Comment by ChuckTheSheep** [comment]
Thank you!
