### ISSUE TITLE
Heli mod not working

### ISSUE THREAD

**Issue by McBeer89** [sharkster91/ExpandedHelicopterEvents#43]
the mod is in the game, i can edit settings but otherwise doesnt seem to be functioning. Here is a link to our mod collection https://steamcommunity.com/sharedfiles/filedetails/?id=271013168
[server-console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7908362/server-console.txt)
7

**Comment by ChuckTheSheep** [comment]
Closing as per discussion in steam workshop. Events should start occurring after day 60ish. Open another ticket if nothing occurs for a week.
