### ISSUE TITLE
PJ

### ISSUE THREAD

**Issue by EstherOrphan** [sharkster91/ExpandedHelicopterEvents#44]
qsdqsd

**Comment by EstherOrphan** [comment]
[console.zip](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7909067/console.zip)

**Comment by ChuckTheSheep** [comment]
You need to figure out what mod is doing this:
`LOG  : General     , 1642719110062> None
LOG  : General     , 1642719110078> None
LOG  : General     , 1642719110095> None
LOG  : General     , 1642719110112> None
LOG  : General     , 1642719110130> None
LOG  : General     , 1642719110145> None
LOG  : General     , 1642719110162> None
LOG  : General     , 1642719110179> None
LOG  : General     , 1642719110196> None
LOG  : General     , 1642719110212> None
LOG  : General     , 1642719110230> None
LOG  : General     , 1642719110245> None
LOG  : General     , 1642719110263> None
LOG  : General     , 1642719110279> None
LOG  : General     , 1642719110295> None
LOG  : General     , 1642719110312> None
LOG  : General     , 1642719110328> None
LOG  : General     , 1642719110346> None
LOG  : General     , 1642719110362> None
LOG  : General     , 1642719110378> None
LOG  : General     , 1642719110396> None
LOG  : General     , 1642719110411> None
LOG  : General     , 1642719110429> None
LOG  : General     , 1642719110446> None
LOG  : General     , 1642719110462> None
LOG  : General     , 1642719110479> None
LOG  : General     , 1642719110495> None
LOG  : General     , 1642719110512> None
LOG  : General     , 1642719110529> None
LOG  : General     , 1642719110546> None
LOG  : General     , 1642719110562> None`

Tell them to not do this.

**Comment by ChuckTheSheep** [comment]
Closing as per DM discussion.
