### ISSUE TITLE
Unable to dismantle crashed helicopter parts.

### ISSUE THREAD

**Issue by AdeptSephiel** [sharkster91/ExpandedHelicopterEvents#47]
Cannot dismantle any crashed helicopter parts even while having Propane Torch and Welder Mask equipped. (see screenshot).

The Welder Mask appears as if not present.

![20220122232910_1](https://user-images.githubusercontent.com/93302474/150666500-f4ee66aa-93e6-43ff-aa3a-fef58a1c357c.jpg)

**Comment by AdeptSephiel** [comment]
Update:

Figured out what the bug here is: If the Welder Mask is marked as `Favorite` - it is not being taken into the account for the dismantle recipe and appears as if not present. However, removing the 'Favorite' from Welder Mask corrects that.

'Propane Torch' is not affected by the presence or lack of the 'Favorite' tag.

**Comment by ChuckTheSheep** [comment]
Strange... thanks for taking time to experiment!
