### ISSUE TITLE
Helicopter Events not triggering (dedicated server)

### ISSUE THREAD

**Issue by chroba89** [sharkster91/ExpandedHelicopterEvents#49]
Coming from the Steam comments, wanted to post these logs and help solve this mystery of events not triggering with the Scheduler.

I truncated to console logs, but I can attach more if that will help troubleshooting. To explain, I logged into the server in debug mode and was pleasantly surprised with a new scheduled event added to the scheduler (news_chopper d120 h22) and another (jet d120 h21). I believe the Jet event was scheduled after hour-21 so I did not expect it to trigger, but I waited until 22:10 in-game and as you can see, no news_chopper triggered.

LOG  : General     , 1643034355914> 1,088,371,879> --- eHeliEventsOnSchedule:  daysIntoApoc: 120  nights-surv: 120  hr: 19
LOG  : General     , 1643034355914> 1,088,371,880> ------ [1]  day:92 time:14 id:jet done:false
LOG  : General     , 1643034355915> 1,088,371,880> ------ [2]  day:91 time:7 id:jet done:false
LOG  : General     , 1643034355915> 1,088,371,881> ------ [4]  day:92 time:6 id:military done:false
LOG  : General     , 1643034355915> 1,088,371,881> ------ [6]  day:92 time:15 id:news_chopper done:false
LOG  : General     , 1643034355916> 1,088,371,881> ------ [7]  day:91 time:19 id:jet done:false
LOG  : General     , 1643034355916> 1,088,371,882> ------ [3]  day:91 time:7 id:news_chopper done:false
LOG  : General     , 1643034355916> 1,088,371,882> ------ [8]  day:90 time:7 id:jet done:false
LOG  : General     , 1643034466195> 1,088,482,160> 1643034466194 znet: ZNetFriends::OnPersonaStateChange
LOG  : General     , 1643034474160> 1,088,490,125>  -Scheduled: news_chopper [Day:120 Time:22]
LOG  : General     , 1643034516890> 1,088,532,856> --- eHeliEventsOnSchedule:  daysIntoApoc: 120  nights-surv: 120  hr: 20
LOG  : General     , 1643034516891> 1,088,532,857> ------ [1]  day:92 time:14 id:jet done:false
LOG  : General     , 1643034516891> 1,088,532,858> ------ [2]  day:91 time:7 id:jet done:false
LOG  : General     , 1643034516891> 1,088,532,858> ------ [4]  day:92 time:6 id:military done:false
LOG  : General     , 1643034516892> 1,088,532,858> ------ [6]  day:92 time:15 id:news_chopper done:false
LOG  : General     , 1643034516892> 1,088,532,859> ------ [7]  day:91 time:19 id:jet done:false
LOG  : General     , 1643034516893> 1,088,532,859> ------ [3]  day:91 time:7 id:news_chopper done:false
LOG  : General     , 1643034516893> 1,088,532,860> ------ [8]  day:90 time:7 id:jet done:false
LOG  : General     , 1643034516893> 1,088,532,860> ------ [9]  day:120 time:22 id:news_chopper done:false
LOG  : General     , 1643034624269> 1,088,640,235>  -Scheduled: jet [Day:120 Time:21]
LOG  : General     , 1643034757347> 1,088,773,315> Zombie: removing stale zombie 5000 id=5655
LOG  : General     , 1643034761346> 1,088,777,314> 1643034761346 znet: ZNetFriends::OnPersonaStateChange
LOG  : General     , 1643034800171> 1,088,816,139> --- eHeliEventsOnSchedule:  daysIntoApoc: 120  nights-surv: 120  hr: 22
LOG  : General     , 1643034800172> 1,088,816,141> ------ [1]  day:92 time:14 id:jet done:false
LOG  : General     , 1643034800173> 1,088,816,141> ------ [2]  day:91 time:7 id:jet done:false
LOG  : General     , 1643034800174> 1,088,816,142> ------ [4]  day:92 time:6 id:military done:false
LOG  : General     , 1643034800174> 1,088,816,143> ------ [6]  day:92 time:15 id:news_chopper done:false
LOG  : General     , 1643034800175> 1,088,816,143> ------ [7]  day:91 time:19 id:jet done:false
LOG  : General     , 1643034800175> 1,088,816,144> ------ [3]  day:91 time:7 id:news_chopper done:false
LOG  : General     , 1643034800176> 1,088,816,144> ------ [8]  day:90 time:7 id:jet done:false
LOG  : General     , 1643034800177> 1,088,816,145> ------ [9]  day:120 time:22 id:news_chopper done:false
LOG  : General     , 1643034800177> 1,088,816,146> ------ [10]  day:120 time:21 id:jet done:false

**Comment by chroba89** [comment]
![Screenshot 2022-01-24 154300](https://user-images.githubusercontent.com/37310515/150804049-4cf060c9-c345-49a8-bb81-1919057915ba.png)

**Comment by ChuckTheSheep** [comment]
Can you read the log and confirm what the ending of this line is `Expanded Helicopter Events: ver:`

**Comment by ChuckTheSheep** [comment]
Related: https://github.com/sharkster91/ExpandedHelicopterEvents/issues/50

**Comment by ChuckTheSheep** [comment]
Stale but related: https://github.com/sharkster91/ExpandedHelicopterEvents/issues/48

**Comment by Cladicus** [comment]
Hey Chuck, Johnny Dollar from issue 50.
Here's what my version says
1643117516880> Expanded Helicopter Events: ver:0.3.6-HOTFIX-SchedulerMP

**Comment by chroba89** [comment]
[server-console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7942615/server-console.txt)

**Comment by chroba89** [comment]
'Expanded Helicopter Events: ver:0.3.6-HOTFIX-SchedulerMP' shows up in my console.txt when I launch in Solo w/ the mod enabled, but it does not generate in my server-console.txt
I cleared the EHE & EasyConfig from the directories, removed the manifest and relaunched the server just to be sure that it was the updated version

**Comment by ChuckTheSheep** [comment]
That line should appear in a coop-console.txt if there is one.

**Comment by chroba89** [comment]
coop-console.txt is only populated by non-dedicated MP servers, mine hasn't been written to in over a month (prior to installing the mod)

I had previously removed the EHE and EasyConfig from the server mods, deleted the manifest and reinstalled the mods per the troubleshooting in the steam thread, on more than one occasion: Im sure it matches the version my client (single player games use) which was .3.6-HOTFIX-SchedulerMP

**Comment by ChuckTheSheep** [comment]
Should be fixed with the scheduler hotfix 2.
