### ISSUE TITLE
Issue - Helis getting stuck near tall buildings

### ISSUE THREAD

**Issue by Eazzy4** [sharkster91/ExpandedHelicopterEvents#52]
Explained in steam discussions, here's the log file:

[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7953915/console.txt)

**Comment by ChuckTheSheep** [comment]
Do you remember what the stuck helicopter sounded like?

**Comment by Eazzy4** [comment]
Checked the audio in the mod files, the one that was stuck is heli_loop.ogg

**Comment by ChuckTheSheep** [comment]
Should be fixed with yesterday's hot-fix. Open a new issue if it occurs again.
