### ISSUE TITLE
Dropping console here

### ISSUE THREAD

**Issue by Shyzle** [sharkster91/ExpandedHelicopterEvents#53]
Just dropping the console and server console log here, everything seemed smooth while playing. Supply drops worked, IRS attacked me and dropped fliers, alien ship crashed (I will note the door square things on the ground were a little broken on the UFO tho, one door was showing on the top side of the UFO while the other box was 3 or 4 tiles off to the left not even on the vehicle itself, maybe the trunk to it or something?)
[server-console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7962902/server-console.txt)
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7962903/console.txt)

**Comment by ChuckTheSheep** [comment]
Thank you!
