### ISSUE TITLE
When starting the server, it gives an error *missing scripts/media...*

### ISSUE THREAD

**Issue by Selmip** [sharkster91/ExpandedHelicopterEvents#56]
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/8008461/console.txt)
[coop-console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/8008463/coop-console.txt)

**Comment by Selmip** [comment]
I think I need to start a new game. And besides, I use not only this mod. Hope this doesn't happen again

**Comment by ChuckTheSheep** [comment]
This is not an issue with this mod - this means you did not properly update your server.
