### ISSUE TITLE
[Suggestion] Drop "cure" like in Dying Light

### ISSUE THREAD

**Issue by ClassyDino** [sharkster91/ExpandedHelicopterEvents#57]
I would be surprised if no one has suggested this before, but events like the Samaritans should drop crates of syringes with a sort of vaccine that slows down the rate of zombie infection. Not cure it, but slow it down, Planetalgol recently [released ](https://steamcommunity.com/sharedfiles/filedetails/?id=2709215581) a mod that adds a syringe that temporarily stops an infected player from turning. I think games like Dying Light, or Dead rising 2 both had versions of this, and it seems like a more interesting version of a temporary "cure" than just finding them in a military base or on random zombies.

**Comment by ChuckTheSheep** [comment]
Not really in the scope of this mod. Those mods can easily add their cures to our loot distributions though.
