### ISSUE TITLE
No helicopter events, even if the frequency is set to frequent. 

### ISSUE THREAD

**Issue by Gamemoder5646** [sharkster91/ExpandedHelicopterEvents#62]
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/8204481/console.txt)
I already tried updating, reloading and uninstalling the mod

**Comment by jackdenkin1374** [comment]
I have same issue here as well.
Looking at console.txt, it suggests some failed LuaManager, possibly failing to load stuff.
Here is a basic log with the game restarting and enabling just expanded + weird edition with cheatmenu.
[consoleafterrestart.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/8210716/consoleafterrestart.txt)

Another with a bunch of mods disabled initially.
[consolejustexpand.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/8210717/consolejustexpand.txt)

And a log with a bunch of mods enabled. Probably don't need this given the above two.
[consolelotsofmods.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/8210719/consolelotsofmods.txt)
