### ISSUE TITLE
Crash when opening a crate

### ISSUE THREAD

**Issue by federicoroma1981** [sharkster91/ExpandedHelicopterEvents#65]
Hi, after the firt helicopter event I saw on the bottom right of the screen some error messages (error 5, error 7 and other) but the game continued to work, I followed the indication till the crate but everytime I try to open it the game crashes. I don't know why. Can you help me to understand why? I attach my file console.txt

[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/8598490/console.txt)

**Comment by ChuckTheSheep** [comment]
Does this still occur?

**Comment by ChuckTheSheep** [comment]
Can you try to play the game with no other mod installed. It seems to be an error coming from opening boxes.
