### ISSUE TITLE
Error in cosole unable to get any Heli Events to schedule

### ISSUE THREAD

**Issue by Restiphani** [sharkster91/ExpandedHelicopterEvents#66]
I have both mods loaded and I have tried resubscribing to the mods and even changing the load order.

See below for the errors being shown

LOG : General , 1657033159161> 37,850,082> EHE: SCHEDULED-LAUNCH INFO: HELI ID:15 - day:9 time:18 id:military done:false
LOG : General , 1657033159162> 37,850,082> -- [eHeliEvent_engage]: HELI HELI 0 (<none>) [false] selecting targets <0> x
LOG : General , 1657033159162> 37,850,082> --- HELI HELI 0 (<none>) [false]- WARN: unable to find target: grabbing random square nearby.
LOG : General , 1657033159162> 37,850,082> --- HELI HELI 0 (<none>) [goHome]: unable to go home; unlaunching.
LOG : General , 1657033159162> 37,850,082> ---- UN-LAUNCH: HELI 0 (<none>) [goHome] (x:?, y:?) day:9 hour:18
LOG : General , 1657033159162> 37,850,082> ------ HELI HELI 0 (<none>) [unLaunched]- ERROR: unable to find square: going home.
LOG : General , 1657033159162> 37,850,083> EHE: SCHEDULED-LAUNCH INFO: HELI ID:18 - day:9 time:18 id:police done:false
LOG : General , 1657033159163> 37,850,083> -- [eHeliEvent_engage]: HELI HELI 0 (<none>) [unLaunched] selecting targets <0> x
LOG : General , 1657033159163> 37,850,083> --- HELI HELI 0 (<none>) [unLaunched]- WARN: unable to find target: grabbing random square nearby.
LOG : General , 1657033159163> 37,850,083> --- HELI HELI 0 (<none>) [goHome]: unable to go home; unlaunching.
LOG : General , 1657033159163> 37,850,083> ---- UN-LAUNCH: HELI 0 (<none>) [goHome] (x:?, y:?) day:9 hour:18
LOG : General , 1657033159163> 37,850,083> ------ HELI HELI 0 (<none>) [unLaunched]- ERROR: unable to find square: going home.
10:59:23
LOG : General , 1657033163169> 37,854,089> EHE: SCHEDULED-LAUNCH INFO: HELI ID:7 - day:7 time:19 id:police done:false
LOG : General , 1657033163170> 37,854,089> -- [eHeliEvent_engage]: HELI HELI 0 (<none>) [unLaunched] selecting targets <0> x
LOG : General , 1657033163170> 37,854,089> --- HELI HELI 0 (<none>) [unLaunched]- WARN: unable to find target: grabbing random square nearby.
LOG : General , 1657033163170> 37,854,089> --- HELI HELI 0 (<none>) [goHome]: unable to go home; unlaunching.
LOG : General , 1657033163170> 37,854,089> ---- UN-LAUNCH: HELI 0 (<none>) [goHome] (x:?, y:?) day:9 hour:19
LOG : General , 1657033163170> 37,854,090> ------ HELI HELI 0 (<none>) [unLaunched]- ERROR: unable to find square: going home.
LOG : General , 1657033163170> 37,854,090> EHE: SCHEDULED-LAUNCH INFO: HELI ID:13 - day:6 time:19 id:news_chopper done:false
LOG : General , 1657033163170> 37,854,090> -- [eHeliEvent_engage]: HELI HELI 0 (<none>) [unLaunched] selecting targets <0> x
LOG : General , 1657033163171> 37,854,090> --- HELI HELI 0 (<none>) [unLaunched]- WARN: unable to find target: grabbing random square nearby.
LOG : General , 1657033163171> 37,854,090> --- HELI HELI 0 (<none>) [goHome]: unable to go home; unlaunching.
LOG : General , 1657033163171> 37,854,090> ---- UN-LAUNCH: HELI 0 (<none>) [goHome] (x:?, y:?) day:9 hour:19
LOG : General , 1657033163171> 37,854,091> ------ HELI HELI 0 (<none>) [unLaunched]- ERROR: unable to find square: going home.

**Comment by ChuckTheSheep** [comment]
Do you have a mod list?

**Comment by ChuckTheSheep** [comment]
Would you be able to only have the EHE related mods on to see if the problem continues - then add a few mods at a time repeating this process?

**Comment by Restiphani** [comment]
I can try doing that, it's just going to take some time.
