### ISSUE TITLE
Helicopter being triggered but nothing happening in game

### ISSUE THREAD

**Issue by SouDescolado** [sharkster91/ExpandedHelicopterEvents#69]
![image](https://user-images.githubusercontent.com/16374855/184391217-d5947a64-77da-4e54-ac6f-616a7035147c.png)

I run a dedicated server, and I am changing the Twitch Integration mod to make it work via Rcon instead of Hotkeys

That being said, there is something funky on the events.

As far as I can tell, the event is being scheduled, it is defining a target and it is "doing something"

However, in game nothing happens. Not a chopper sound, not a marker, anything.

I tried running the hotkey version of the twitch integration too, but also had no success. Is there a way for me to identify what exactly is not doing its job?

**Comment by ChuckTheSheep** [comment]
I believe there may have been a change that is keeping the event on the server side and not showing it to you. I am not sure why this would be the case - will have to be looked into after the next update unfortunately.

**Comment by vizctas** [comment]
Hello. I having the same issue.  

While loading the server MODLESS only expanded helo. Found errors listed below. 
I'm running dedicated server too and everyday on logs a message like : 
-Scheduled: military [Day:13 Time:18]  Appears but nothing happens ingame.  

Thank you in advance. I love your mod like you have no idea!  excelent work!



[13-08-22 18:50:15.814] WARN : Lua , 1660431015814> 218,719,016> LuaManager$GlobalObject.require> require("ExpandedHelicopter00e_EHEGlobalModData") failed.
[13-08-22 18:50:15.814] WARN : Lua , 1660431015814> 218,719,017> LuaManager$GlobalObject.require> require("ExpandedHelicopter01a_MainVariables") failed.

[13-08-22 18:50:15.822] WARN : Lua , 1660431015822> 218,719,025> LuaManager$GlobalObject.require> 
![Screenshot 2022-08-14 165745](https://user-images.githubusercontent.com/38738081/184556340-4a9b0353-7cc3-43e6-a6f9-5326ff1134fe.png)
require("OptionScreens/ServerSettingsScreen") failed.
[13-08-22 18:50:15.822] WARN : Lua , 1660431015822> 218,719,025> LuaManager$GlobalObject.require> require("OptionScreens/SandBoxOptions") failed.

**Comment by kiwi2kiwi** [comment]
I'm getting similar errors on a singleplayer world:
require("ExpandedHelicopter01a_MainVariables") failed
require("ExpandedHelicopter10_EventMarkers") failed
require("ExpandedHelicopter00b_IsoRangeScan") failed
require("ExpandedHelicopter01a_MainVariables") failed

two of which im not sure are connected to the mod:
require("OptionScreens/ServerSettingsScreen") failed
require("OptionScreens/SandBoxOptions") failed


but i did not get:
require("ExpandedHelicopter00e_EHEGlobalModData") failed

**Comment by SouDescolado** [comment]
I identified the problem. I was trying to call the helicopter events serverside, and they need to be called clientside. When I changed in a way that it sent via sendServerCommand and intercepted by the client code, it worked perfectly.
My original error can be closed, however cannot say the others that commented on this issue

**Comment by vizctas** [comment]
It fixed for me too. This issue can be closed

**Comment by SouDescolado** [comment]
Since kiwi already got a separate issue, I am closing this one.
