### ISSUE TITLE
Bug report 6/16/2021

### ISSUE THREAD

**Issue by DestroClub** [sharkster91/ExpandedHelicopterEvents#7]
- Heli sound gets stuck before you quit the game (if there is a river nearby, no shadows, just sound in the water) 

- This mod turns off rain sounds (I disable heli events mod only and rain sounds return) 

- Attach console.txt after found a stuck heli sound (btw I know you guys just turned off error notification without fix the problem) 
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/6661011/console.txt)

**Comment by ChuckTheSheep** [comment]
Thank you for the report.

**Comment by ChuckTheSheep** [comment]
Your log does not appear to show any errors, however, I'll look into the issues reported here.
Could you clarify what "btw I know you guys just turned off error notification without fix the problem"?, thank you.

Side note, what other mods do you have installed? One of them is dumping numbers into the log with no context.

**Comment by ChuckTheSheep** [comment]
Continuing this discussion in #8
