### ISSUE TITLE
que es lo que exactamente no me deja incluir el mod a mi partida ?

### ISSUE THREAD

**Issue by pocho69-oes** [sharkster91/ExpandedHelicopterEvents#70]
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9351910/console.txt)

**Comment by ChuckTheSheep** [comment]
What mods do you have installed?

**Comment by pocho69-oes** [comment]
![Project Zomboid 17_08_2022 3_07_01 p  m](https://user-images.githubusercontent.com/92956083/185233176-54ec6e18-bb4a-43a8-8ebf-9bf86ba12de3.png)
![Project Zomboid 17_08_2022 3_07_15 p  m](https://user-images.githubusercontent.com/92956083/185233185-dbc7e365-0908-4d89-babc-e160d24b3f60.png)
![Project Zomboid 17_08_2022 3_07_34 p  m](https://user-images.githubusercontent.com/92956083/185233195-9b5480d7-df36-4a2f-bd83-804e076c81a3.png)

**Comment by pocho69-oes** [comment]
too much son, sorry
