### ISSUE TITLE
Survival Vests not wearable

### ISSUE THREAD

**Issue by grundyboy34** [sharkster91/ExpandedHelicopterEvents#71]
Found a SRU-21/P Survival Vest in the Louisville Army Surplus store, but it's not wearable. It only has options to Equip Primary and Equip Secondary.

Is this intended?
The only mod I have that I think could be conflicting is Customizable Containers (with the satchels can be worn on back fanny pack slot option)

**Comment by ChuckTheSheep** [comment]
Should be fixed with 96031893748c839779361499f9f2afa81469cb8e
