### ISSUE TITLE
Strange errors about missing files

### ISSUE THREAD

**Issue by kiwi2kiwi** [sharkster91/ExpandedHelicopterEvents#72]
Hey, i spotted this in the console. It seems to be an important error and i've got no clue why it occurrs because these files aren't even in the repo soooooo......
I'm running v41.73 and i've got the latest expanded helicopter events.
I've also got EasyConfigChucked
Also the events really seem to be lacking. I've seen more jet events than chopper events so there may be something wrong.

WARN : Lua         , 1661325287909> LuaManager$GlobalObject.require> require("ExpandedHelicopter01a_MainVariables") failed
few lines inbetween
WARN : Lua         , 1661325382324> LuaManager$GlobalObject.require> require("ExpandedHelicopter10_EventMarkers") failed

EDIT:
these two messages also appeared in the same log file:
WARN : Lua         , 1661325382329> LuaManager$GlobalObject.require> require("ExpandedHelicopter00b_IsoRangeScan") failed
WARN : Lua         , 1661325382329> LuaManager$GlobalObject.require> require("ExpandedHelicopter01a_MainVariables") failed

**Comment by ChuckTheSheep** [comment]
All of those files are in the repo. Are you getting this off Steam?

**Comment by kiwi2kiwi** [comment]
i think it's trying to look for these files in the shared directory since the error appears between two lines loading from the shared directory:
LOG  : Lua         , 1661424576147> Loading: shortened/Zomboid/mods/Expanded Helicopter Events/media/lua/shared/ExpandedHelicopter00e_EHEGlobalModData.lua
WARN : Lua         , 1661424576147> LuaManager$GlobalObject.require> require("ExpandedHelicopter01a_MainVariables") failed
LOG  : Lua         , 1661424576148> Loading: shortened/Zomboid/mods/Expanded Helicopter Events/media/lua/shared/ExpandedHelicopter02a_Presets.lua

The files are indeed in the server and client folders like in this repo. I'll try copying them to the shared folder and see what happens. Also yes these are from steam but i may have moved some mod folders from different versions so that may also be a weak point

**Comment by kiwi2kiwi** [comment]
there's an issue with similar error messages. I added a comment in case it's relevant and connected:  https://github.com/sharkster91/ExpandedHelicopterEvents/issues/69

**Comment by kiwi2kiwi** [comment]
I've temporarily fixed it by moving the missing files from the server folder to the shared folder. I don't know if thix actually fixed it but the mod doesn't throw errors anymore except for the:
require("OptionScreens/SandBoxOptions") failed
require("OptionScreens/ServerSettingsScreen") failed

but i don't know if they are connected to this mod

**Comment by kiwi2kiwi** [comment]
Hmmm didn't work, haven't seen a single chopper or other event

**Comment by kiwi2kiwi** [comment]
Ok I got a chopper supply event now. I did nothing except the previously stated stuff and removing arsenal, brita, sandbox+. Also I did not move the files from the server folder to the shared folder, I only copied them

**Comment by kiwi2kiwi** [comment]
Closing because I think this is "fixed"
