### ISSUE TITLE
event does not stop until client restarts

### ISSUE THREAD

**Issue by ZeeNotic** [sharkster91/ExpandedHelicopterEvents#77]
When an event occurs it goes normally until it comes time for the event to end which then the origin of the sound (the heli,jet, or the air raid siren) will keep playing endlessly until you restart. The type of server i am playing on is one hosted via in game by another friend (no fancy dedicated server stuff or anything like that) and we do play with other mods so could be a another mod causing the issue.  

Below is my consol.txt file hope it helps

[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9502436/console.txt)

**Comment by stuk4** [comment]
Same problem :c

**Comment by ChuckTheSheep** [comment]
This log looks incomplete/cut off and is missing key information.

**Comment by nmlynch94** [comment]
Had this happen today on my dedicated server. Here is the log file from that session. Let me know if I can provide anymore info.
[server-console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9593011/server-console.txt)

**Comment by ChuckTheSheep** [comment]
I doubt the player has this at this point but their console log would be helpful.

**Comment by nmlynch94** [comment]
Here is my console.txt. Comparing the unix timestamps, it appears to span the time of the server-console.txt so hopefully it contains something helpful.
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9595178/console.txt)

If not, I'll provide both the server-console and client console next time it happens. 

Thanks for the mod btw. Is very cool.

**Comment by ChuckTheSheep** [comment]
Thank you very much and thanks for the kind words.

**Comment by nmlynch94** [comment]
No problem! Happened today to one of my players and I grabbed the log file from them. Will provide this last one in case the client one I provided is missing key info:

[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9613268/console.txt)

**Comment by sharkster91** [comment]
We will keep this open, let us know whenever you get another problem
regarding it.
