### ISSUE TITLE
UFO and Heli both start bug

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [sharkster91/ExpandedHelicopterEvents#78]
The event started at my base, a UFO and a Helicopter appeared at the same time, while the sound was buggy and the icons flickered, they were in no hurry to fly away until I decided not to teleport away. After returning, they gone, but UFO'S Sound stuck. 

https://user-images.githubusercontent.com/12477741/188892879-2062342c-2b14-4875-b3e6-3444a2fcd6e4.mp4

**Comment by ZSHADOWWOLF** [comment]
Interestingly, after the relog i get Physical UFO's Vehicle, but its partially stuck in building. But i can't found helicopter
![Project Zomboid Screenshot 2022 09 07 - 22 17 14 84](https://user-images.githubusercontent.com/12477741/188961256-f7ee0451-c80b-400a-809d-5a4cac672844.png)

**Comment by ChuckTheSheep** [comment]
That's what a UFO crash looks like, the fact the sound stayed for the crash should help narrow down what's going on. Thank you.

**Comment by ZSHADOWWOLF** [comment]
But i hear and a Helicopter sound, both with UFO! and indicator show two sound sources

**Comment by ChuckTheSheep** [comment]
Is this issue on-going? There has been a few hotfixes/tweaks since this issue opening. Will re-open if you're still having issues.
