### ISSUE TITLE
HeliCrash bubble's disappear too fast

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [sharkster91/ExpandedHelicopterEvents#79]
This is not the first time I have observed a helicopter crash or other events, but the bubbles disappear too quickly and it is no longer possible to find the crash site.

**Comment by siph** [comment]
I'm having the same issue. The helicopter comes and drops the crate and the crate icon disappears but the helicopter icon stays until the heli leaves the players range.

**Comment by ChuckTheSheep** [comment]
Will increase duration by about 50%.
