### ISSUE TITLE
6.18.2021 Helicopter sound stuck in the river (video attached)

### ISSUE THREAD

**Issue by DestroClub** [sharkster91/ExpandedHelicopterEvents#8]
1) My log file with sound stuck in the in the last bug 
2) No ambient / rain sounds. Today I reinstalled Zomboid and turn on your mod only - nothing changed

https://user-images.githubusercontent.com/85986277/122556307-04187f80-d044-11eb-968e-e8191157244e.MP4

report

**Comment by ChuckTheSheep** [comment]
Marking this as a continuation of #7 

Could you please reattach the log file, it looks like it did not get attached.

**Comment by ChuckTheSheep** [comment]
Marking this as a continuation of #7
Could you please reattach the log file, it looks like it did not get attached.
Remember the log resets on game start, so it should be sent once the game is closed.

The file is found in: 'C:\Users\<username>\Zomboid\console.txt'

**Comment by ChuckTheSheep** [comment]
The "stuck" component of this issue should be fixed. See #9 for sound related portion.
