### ISSUE TITLE
Malformed Packet 21.

### ISSUE THREAD

**Issue by mjvej4f** [sharkster91/ExpandedHelicopterEvents#80]
The issue seems to cause immense lag even when the anticheat is disabled for 21. Everytime me or anyone else who is not in admin mode moves our character, it spams the shit out of my server console. 

The last few lines before I got kicked, probably not too useful:
LOG  : General     , 1663549588257> 64,662,443> NO CONT DISTRIB FOR PART: TruckBed CAR: pursuitspecial
LOG  : General     , 1663549588258> 64,662,444> NO CONT DISTRIB FOR PART: GloveBox CAR: pursuitspecial
LOG  : General     , 1663549588329> 64,662,515> ERROR: Missing translation "RM_d1e063ce-7094-405d-9366-a38e525f2b15"
LOG  : General     , 1663549588385> 64,662,570> Found a new body
LOG  : General     , 1663549588631> 64,662,817> Found a new body
LOG  : General     , 1663549588721> 64,662,907> ERROR: Missing translation "RM_ed5b4fe2-9a64-4ca9-ba70-75614d22a99f"
LOG  : General     , 1663549588996> 64,663,182> Found a new body
LOG  : General     , 1663549589050> 64,663,237> Found a new body
LOG  : General     , 1663549589102> 64,663,288> ERROR: Missing translation "RM_fb1f3cc8-3d8f-4661-8a2f-ffa7e736d14b"
LOG  : General     , 1663549589330> 64,663,516> ERROR: Missing translation "RM_77dd0cbe-15ed-4078-a029-08452b776ab4"
WARN : General     , 1663549596102> 64,670,287> GameServer.kick> The player mjvej4f was kicked. The reason was UI_Policy_Kick, UI_ValidationFailed_Type21
LOG  : General     , 1663549596102> 64,670,288> 1663549596102> znet: Java_zombie_core_raknet_RakNetPeerInterface_disconnect
LOG  : General     , 1663549596123> 64,670,308> 1663549596123> znet: Connection closed: reason=1 port=1
LOG  : General     , 1663549596123> 64,670,309> 1663549596123> znet: Disconnecting client #0 SteamID=76561198046270666
LOG  : General     , 1663549596160> 64,670,346> IsoChunk.removeFromWorld: vehicle wasn't removed from world id=255
LOG  : General     , 1663549596164> 64,670,350> IsoChunk.removeFromWorld: vehicle wasn't removed from world id=254
LOG  : General     , 1663549596181> 64,670,367> IsoChunk.removeFromWorld: vehicle wasn't removed from world id=253
LOG  : General     , 1663549596182> 64,670,368> IsoChunk.removeFromWorld: vehicle wasn't removed from world id=252
LOG  : General     , 1663549596187> 64,670,373> IsoChunk.removeFromWorld: vehicle wasn't removed from world id=251
LOG  : General     , 1663549596187> 64,670,373> IsoChunk.removeFromWorld: vehicle wasn't removed from world id=250
LOG  : General     , 1663549596350> 64,670,536> 1663549596350> znet: OnValidateAuthTicketResponse response=6 SteamID=76561198046270666
LOG  : General     , 1663549599143> 64,673,329> 1663549599143> znet: Finally disconnected client 76561198046270666

**Comment by mjvej4f** [comment]
WARN : Multiplayer , 1663550343079> 65,417,265> PacketTypes$PacketAuthorization.isAuthorized> Unauthorized packet ClimateManagerPacket () was received from user="mjvej4f" () ip 154.149.173.36 76561198046270666

**Comment by mjvej4f** [comment]
I forgot to mention that when it's spamming these messages, it lags unbearably

**Comment by ChuckTheSheep** [comment]
Why do you think this mod is related?

**Comment by ChuckTheSheep** [comment]
No worries, I was just curious. Appreciate the tedious work.

**Comment by ChuckTheSheep** [comment]
There has been a few hotfixes/updates since Sept 20th, if this issue is still occurring let me know and this will be re-opened.
