### ISSUE TITLE
[unstable 41.78] SandboxVars.ExpandedHeli.SchedulerDuration is nil

### ISSUE THREAD

**Issue by RobRendell** [sharkster91/ExpandedHelicopterEvents#84]
On the unstable 41.78 branch, I'm able to reproduce this issue reliably by starting a new game (I tried with Apocalypse and Custom Sandbox settings).

The mod throws a Lua error every game hour from eHeliEvent_ScheduleNew, and debugging showed that SandboxVars.ExpandedHeli.SchedulerDuration is nil.

The attached [console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9932882/console.txt) is from a session where I just started a new game and then quit out once the error had occurred.

**Comment by ChuckTheSheep** [comment]
I believe this was addressed in an earlier hotfix. Feel free to comment if I'm mistaken.
