### ISSUE TITLE
Helicopter flies straight over head and leaves.

### ISSUE THREAD

**Issue by CallMeLance** [sharkster91/ExpandedHelicopterEvents#87]
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9983499/console.txt)
This is from start to finish of joining the server in debug mode. I recreated error using debug mode. It flies over head and leaves instantly, just like a jet usually would do. I have everything on frequent. 
According to my friend who is on the same server as I am and who I play with, a helicopter managed to actually crash and this is all that was there.
![image](https://user-images.githubusercontent.com/54371426/201171448-6270751b-9c9e-4357-9a77-7566e2214323.png)
I attempted to recreate the error in singleplayer mode without Britas mod pack and with it to see if that was the issue, however, it worked like a charm with both enabled. I am unsure if it has to deal with multiplayer or other mods I have added.

**Comment by ChuckTheSheep** [comment]
Survivor helis do not hover over the player.

That being said, you reported jets hanging/getting stuck - was that during this session? Are you still experiencing those issues?

**Comment by CallMeLance** [comment]
Jets hang on every session everytime I start up the server. I have never had a supply drop drop. I've never had any other events except the occasional jet that flies overhead and the sound gets stuck. Or when a helicopter flies over, it never does anything except leave then that sound also gets stuck.

**Comment by ChuckTheSheep** [comment]
I can not replicate jets getting stuck since the last update. Are you able to get the console-server.txt from the host machine?

**Comment by ChuckTheSheep** [comment]
I was not able to confirm the issues directly but other errors have been addressed since Nov 11. Let me know if the issue is still occurring and I'll reopen this.
