### ISSUE TITLE
EHE not working at all on nosteam dedicated server.

### ISSUE THREAD

**Issue by trashcanhands** [sharkster91/ExpandedHelicopterEvents#88]
I cannot for the life of me get this to work on my server. I run a nosteam dedicated server. I don't see any events trigger at all. Occasionally, I will see things like AEBS_military, etc. come over the radio, but events never trigger, or even attempt to trigger from what I can tell in the logs. The only errors I get are during the startup of the server. Server-log attached.

[server-console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9995639/server-console.txt)

**Comment by ChuckTheSheep** [comment]
Sorry for the late reply, I don't see any events or information to work off of.
Was this log while the server was running for a period of time?

Some things that could help figure out the problem:
- What is your starting day?
- Is this an on-going save you're trying to add the mod to?

If you read through the FAQ on steam, there's a few caveats to running the mod.

**Comment by trashcanhands** [comment]
Hey man, no worries. Reply was actually way quicker than expected seeing as you're getting slammed. 
Sorry for the complete lack of information on my part, could have saved some time.

Starting day was Jun/July 9, or whatever the default is. 
I had initially tried it on an existing world, but ended up starting a new one, that log is from the new one. It's also only the log of the server being booted, as I originally didn't see much on the console log after playing. This was a mistake on my part and I've attached a console and server log from the same world, with about 2-3 hours of play time that I actually just ended.

Also, the only settings I've changed are Police,News,Military are set to Common, all others remain Uncommon and I changed the starting day to 1 from the default 0, basically because I was unsure if that changed anything.

I have read all of the FAQ and majority of comments.
[server-console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/10008697/server-console.txt)
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/10008698/console.txt)

Let me know if there is anything I can do to help.

**Comment by ChuckTheSheep** [comment]
Will be looking over these, thanks for the detailed response!

**Comment by ChuckTheSheep** [comment]
Very odd, there just isn't anything - which is good in that nothing is broken or throwing errors. We recently updated the mod to have more debug messages - would you mind trying to run a server for a few in game days (all events on frequent) with no other mods but EHE and EasyConfigChucked?

**Comment by trashcanhands** [comment]
I can absolutely do that. I will resub to both mods and let one run tomorrow and will post the logs and any other details I may have. 

Glad to see someone staying commited to their creation!

**Comment by trashcanhands** [comment]
Hey brother, 
I ran a clean server, with only the ECC and EHE mods active, for about 3 game days. Everything set to Frequent. 
Looking through the logs, I had 2 jet events get scheduled. I saw the AEBS_jet text appear over the radio during the first expected launch time (Day 2)(13:00), but it appears it was unlaunched. There are actually some Stack Traces in the logs this time, though. I hope this helps and if there is anything else I can do, just let me know.

[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/10023965/console.txt)
[server-console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/10023966/server-console.txt)
[coop_console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/10023967/coop_console.txt)

**Comment by ChuckTheSheep** [comment]
Thanks for the effort. Not sure why the radio messages aren't getting translated.

**Comment by ChuckTheSheep** [comment]
Found the issue with the specific error, but the events should have fired / been experienced.

Listed target is "Hunter Vance" - but it appears the jet timed out after taking too long.

**Comment by ChuckTheSheep** [comment]
Is this issue still persisting by chance?

**Comment by trashcanhands** [comment]
I was actually just playing and I had a News Heli trigger. It flew over and past me. The event marker popped up and followed it properly. I didn't see a shadow, but I believe that was another issue you've been working on, or it could have just not flown close enough to me for me to see it, but it seems the issue is fixed for me! Thank you so much, my dude. I love this mod. :)

**Comment by ChuckTheSheep** [comment]
It can remain up for a few more days just to be sure. Thanks for the work! 👍
